language: ruby
cache: bundler
rvm:
  - 2.2.0
  - 2.4.0
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
matrix:
  exclude:
  - rvm: 2.2.0
    gemfile: gemfiles/rails_5.gemfile
before_install:
  - "rm -f Gemfile.lock"
install: "bundle install --jobs=3 --retry=3"
script: "bundle exec rspec spec"
